// builds (or rebuilds) /test/unit/require-all-utilities.js

const fs = require('fs')
const path = require('path')

const {standardUtilityFilenames, utilitiesDir} = require('../../utilities/lib/helpers')

const filenames = standardUtilityFilenames()

const fileContents = [
  '// This file is automatically generated by /bin/buildRequireAllUtils.js',
  '// Any changes to this file will be overwritten',
  '// This file is used by /bin/graphDeps.js to generate a module dependency diagram',
  '',
  filenames.map(u => `const ${path.basename(u, '.js')} = require('${path.join(utilitiesDir, u)}')`),
  '',
  'module.exports = {',
  filenames.map((u, i) => `  ${path.basename(u, '.js')}${i === filenames.length - 1 ? '' :','}`),
  '}'
].flat().join('\n')

const buildRequireAllUtils = filePath => fs.writeFileSync(filePath, fileContents)

module.exports = buildRequireAllUtils
