// builds (or rebuilds) require-all-concerns.js

const fs = require('fs')
const path = require('path')

const {concernsDir} = require('../../utilities/lib/helpers')

const {concernList} = require('../test-helpers')

const pathList = concernList()

const fileContents = [
  '// This file is automatically generated by /bin/buildRequireAllConcerns.js',
  '// Any changes to this file will be overwritten',
  '// This file is used by /bin/graphDeps.js to generate a module dependency diagram',
  '',
  pathList.map(c => `const ${path.basename(c, '.js')} = require('${path.isAbsolute(c) ? c : path.join(concernsDir, c)}')`),
  '',
  'module.exports = {',
  pathList.map((c, i) => `  ${path.basename(c, '.js')}${i === pathList.length - 1 ? '' :','}`),
  '}'
].flat().join('\n')

const buildRequireAllConcerns = filePath => fs.writeFileSync(filePath, fileContents)

module.exports = buildRequireAllConcerns
